export const ACL_USER_SET_USER = "ACL_USER_SET_USER";
export const ACL_USERS_CHANGE = "ACL_USERS_CHANGE";
export const ACL_USERS_REQUEST_ERROR = "ACL_USERS_REQUEST_ERROR";
export const ACL_USER_CREATE_ERROR = "ACL_USER_CREATE_ERROR";
export const ACL_USER_CREATE_SUCCESS = "ACL_USER_CREATE_SUCCESS";
export const ACL_LDAP_USER_CREATE_ERROR = "ACL_LDAP_USER_CREATE_ERROR";
export const ACL_LDAP_USER_CREATE_SUCCESS = "ACL_LDAP_USER_CREATE_SUCCESS";
export const ACL_USER_DELETE_ERROR = "ACL_USER_DELETE_ERROR";
export const ACL_USER_DELETE_SUCCESS = "ACL_USER_DELETE_SUCCESS";
export const ACL_USER_DETAILS_FETCH_START = "ACL_USER_DETAILS_FETCH_START";
export const ACL_USER_DETAILS_FETCHED_ERROR = "ACL_USER_DETAILS_FETCHED_ERROR";
export const ACL_USER_DETAILS_FETCHED_SUCCESS =
  "ACL_USER_DETAILS_FETCHED_SUCCESS";
export const ACL_USER_DETAILS_GROUPS_CHANGE = "ACL_USER_DETAILS_GROUPS_CHANGE";
export const ACL_USER_DETAILS_GROUPS_ERROR = "ACL_USER_DETAILS_GROUPS_ERROR";
export const ACL_USER_DETAILS_PERMISSIONS_CHANGE =
  "ACL_USER_DETAILS_PERMISSIONS_CHANGE";
export const ACL_USER_DETAILS_PERMISSIONS_ERROR =
  "ACL_USER_DETAILS_PERMISSIONS_ERROR";
export const ACL_USER_DETAILS_USER_CHANGE = "ACL_USER_DETAILS_USER_CHANGE";
export const ACL_USER_DETAILS_USER_ERROR = "ACL_USER_DETAILS_USER_ERROR";
export const ACL_USER_UPDATE_ERROR = "ACL_USER_UPDATE_ERROR";
export const ACL_USER_UPDATE_SUCCESS = "ACL_USER_UPDATE_SUCCESS";
