#!/usr/bin/env bash

# Set CLUSTER_URL on your command line and source this file to obtain auth
# related env vars for the given cluster in case it is using the default
# credentials. For convenience cypress-readable env-vars are exported along, so
# you could do the following
#
#     source PATH_TO_THIS_SCRIPT
#     # all auth-related env-vars are now loaded
#     npx cypress open --config-file=cypress.system-tests.json
#

###############################################################################
#                  MAKE SURE ENV IS SET AND DEPS ARE PRESENT                  #
###############################################################################
if [ -z "$CLUSTER_URL" ]; then echo "ERROR: Please pass a 'CLUSTER_URL'. Maybe you can use CLUSTER_URL=http://localhost:4200/ ?"; exit 1; fi
if [ -z "$(which jq)" ]; then echo "ERROR: Please install jq from https://stedolan.github.io/jq/"; exit 1; fi
if [ -z "$(which curl)" ]; then echo "ERROR: Please install curl from https://curl.haxx.se/"; exit 1; fi

DCOS_USERNAME=${DCOS_USERNAME:-bootstrapuser}
DCOS_PASSWORD=${DCOS_PASSWORD:-deleteme}

###############################################################################
#                           GATHER AUTH INFORMATION                           #
###############################################################################
VARIANT=$(curl -s --insecure -H "Content-Type: application/json" "$CLUSTER_URL/dcos-metadata/dcos-version.json" | jq -r '.["dcos-variant"]')

CLEAR_CLUSTER_AUTH_INFO=$( [ "$VARIANT" = "enterprise" ] \
  && echo '{"uid": "'$DCOS_USERNAME'", "description": "Bootstrap superuser", "is_remote": false}' \
  || echo '{"uid": "albert@bekstil.net", "description": "albert" }' \
)

# unfortunately osx and linux have different base64 implementations
export CLUSTER_AUTH_INFO=$( [[ "$OSTYPE" == "darwin"* ]] \
  && echo $CLEAR_CLUSTER_AUTH_INFO | base64 \
  || echo $CLEAR_CLUSTER_AUTH_INFO | base64 -w0 \
)


#
# From : https://github.com/dcos/dcos/blob/master/test_util/helpers.py#L35
#
# Token valid until 2036 for user albert@bekstil.net
#    {
#        "email": "albert@bekstil.net",
#        "email_verified": true,
#        "iss": "https://dcos.auth0.com/",
#        "sub": "google-oauth2|109964499011108905050",
#        "aud": "3yF5TOSzdlI45Q1xspxzeoGBe9fNxm9m",
#        "exp": 2090884974,
#        "iat": 1460164974
#    }
#
BODY_OSS="{\"token\": \"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik9UQkVOakZFTWtWQ09VRTRPRVpGTlRNMFJrWXlRa015Tnprd1JrSkVRemRCTWpBM1FqYzVOZyJ9.eyJlbWFpbCI6ImFsYmVydEBiZWtzdGlsLm5ldCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJodHRwczovL2Rjb3MuYXV0aDAuY29tLyIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTA5OTY0NDk5MDExMTA4OTA1MDUwIiwiYXVkIjoiM3lGNVRPU3pkbEk0NVExeHNweHplb0dCZTlmTnhtOW0iLCJleHAiOjIwOTA4ODQ5NzQsImlhdCI6MTQ2MDE2NDk3NH0.OxcoJJp06L1z2_41_p65FriEGkPzwFB_0pA9ULCvwvzJ8pJXw9hLbmsx-23aY2f-ydwJ7LSibL9i5NbQSR2riJWTcW4N7tLLCCMeFXKEK4hErN2hyxz71Fl765EjQSO5KD1A-HsOPr3ZZPoGTBjE0-EFtmXkSlHb1T2zd0Z8T5Z2-q96WkFoT6PiEdbrDA-e47LKtRmqsddnPZnp0xmMQdTr2MjpVgvqG7TlRvxDcYc-62rkwQXDNSWsW61FcKfQ-TRIZSf2GS9F9esDF4b5tRtrXcBNaorYa9ql0XAWH5W_ct4ylRNl3vwkYKWa4cmPvOqT5Wlj9Tf0af4lNO40PQ\"}"
BODY_EE='{ "uid": "'$DCOS_USERNAME'", "password": "'$DCOS_PASSWORD'" }'
BODY=$( [ "$VARIANT" = "enterprise" ] && echo $BODY_EE || echo $BODY_OSS)
export CLUSTER_AUTH_TOKEN=$(curl -s --insecure -X "POST" -H "Content-Type: application/json" --data "$BODY" "$CLUSTER_URL/acs/api/v1/auth/login" | jq -r ".token")
export DCOS_CLUSTER_SETUP_ACS_TOKEN=$CLUSTER_AUTH_TOKEN

if [[ ! $CLUSTER_AUTH_TOKEN || $CLUSTER_AUTH_TOKEN == "null" ]]; then
  echo "\n===================================== ERROR ===================================="
  echo "Could not obtain CLUSTER_AUTH_TOKEN for cluster $CLUSTER_URL";
  echo "Tried to authenticate with $BODY."
  echo 'You may be able to fix that by providing $DCOS_USERNAME and $DCOS_PASSWORD.'
  echo "================================================================================\n\n"
  exit 1;
fi

export CYPRESS_CLUSTER_AUTH_INFO="$CLUSTER_AUTH_INFO"
export CYPRESS_CLUSTER_AUTH_TOKEN="$CLUSTER_AUTH_TOKEN"
export CYPRESS_CLUSTER_URL="$CLUSTER_URL"
# usually only set in a CI env
export CYPRESS_TEST_UUID=${TEST_UUID:-local}
