#!/usr/bin/env bash

# Example: find_debug_directives ./test src/js/components/__tests__/Component-test.js
find_debug_directives(){
  if [[ -z $* ]]; then exit 0; fi

  grep -E -R -s --color=always "((it|describe|test|context)\.only)\(" $*
}
