#!/bin/bash

# This script is intended to be called by the ci scripts, please dont 
# execute it directly.

## Configuration
#####################################################################

SCRIPT_PATH="$(dirname "$0")/$(dirname "$(readlink "$0")")"

PROJECT_ROOT="$( cd "${SCRIPT_PATH}/../../../" && pwd )"

DCOS_BRANCH=${DCOS_BRANCH:-""}

PKG_VERSION=${PKG_VERSION:-""}

## Check Params
#####################################################################

if [ -z "${DCOS_BRANCH}" ] || [ -z "${PKG_VERSION}" ]; then
  echo "Cant Create Bump without given \$DCOS_BRANCH and \$PKG_VERSION!"
  exit 1
fi

## Create DC/OS Bump PR
#####################################################################

CHANGELOG=$(${SCRIPT_PATH}/generate-changelog)

cd dcos-nightly

TEMPLATE=$(curl -H "Accept: application/vnd.github.v3.raw" https://api.github.com/repos/dcos/dcos/contents/PULL_REQUEST_TEMPLATE.md)
TASKS_HEAD="Corresponding DC/OS tickets (obligatory)"

PR_BODY=$(echo "${TEMPLATE}" | sed "s@${TASKS_HEAD}@${TASKS_HEAD}<br /><br />${CHANGELOG}@")
PR_BODY_NO_NEWLINES=$(echo "${PR_BODY//$'\n'/<br />}")
PR_BODY_NO_NEWLINES_NO_HEADING=$(echo "${PR_BODY_NO_NEWLINES//$'#'/}")

pullRequest="{
  \"title\": \"Bump DC/OS UI Package ${PKG_VERSION}\",
  \"body\": \"${PR_BODY_NO_NEWLINES_NO_HEADING}\",
  \"head\": \"mesosphere:${DCOS_BRANCH}\",
  \"base\": \"master\"
}"

curl -H "Content-Type: application/json" -u "$GIT_USER:$GIT_PASSWORD" -X POST -d "${pullRequest}" https://api.github.com/repos/dcos/dcos/pulls