export const MESOS_INITIALIZE_LOG_CHANGE = "MESOS_INITIALIZE_LOG_CHANGE";
export const MESOS_INITIALIZE_LOG_REQUEST_ERROR =
  "MESOS_INITIALIZE_LOG_REQUEST_ERROR";
export const MESOS_LOG_CHANGE = "MESOS_LOG_CHANGE";
export const MESOS_LOG_REQUEST_ERROR = "MESOS_LOG_REQUEST_ERROR";
export const MARATHON_APPS_CHANGE = "MARATHON_APPS_CHANGE";
export const MARATHON_APPS_ERROR = "MARATHON_APPS_ERROR";
export const MARATHON_DEPLOYMENT_ROLLBACK_ERROR =
  "MARATHON_DEPLOYMENT_ROLLBACK_ERROR";
export const MARATHON_DEPLOYMENT_ROLLBACK_SUCCESS =
  "MARATHON_DEPLOYMENT_ROLLBACK_SUCCESS";
export const MARATHON_DEPLOYMENTS_CHANGE = "MARATHON_DEPLOYMENTS_CHANGE";
export const MARATHON_DEPLOYMENTS_ERROR = "MARATHON_DEPLOYMENTS_ERROR";
export const MARATHON_GROUP_CREATE_ERROR = "MARATHON_GROUP_CREATE_ERROR";
export const MARATHON_GROUP_CREATE_SUCCESS = "MARATHON_GROUP_CREATE_SUCCESS";
export const MARATHON_GROUP_DELETE_ERROR = "MARATHON_GROUP_DELETE_ERROR";
export const MARATHON_GROUP_DELETE_SUCCESS = "MARATHON_GROUP_DELETE_SUCCESS";
export const MARATHON_GROUP_EDIT_ERROR = "MARATHON_GROUP_EDIT_ERROR";
export const MARATHON_GROUP_EDIT_SUCCESS = "MARATHON_GROUP_EDIT_SUCCESS";
export const MARATHON_GROUPS_CHANGE = "MARATHON_GROUPS_CHANGE";
export const MARATHON_GROUPS_ERROR = "MARATHON_GROUPS_ERROR";
export const MARATHON_INSTANCE_INFO_SUCCESS = "MARATHON_INSTANCE_INFO_SUCCESS";
export const MARATHON_INSTANCE_INFO_ERROR = "MARATHON_INSTANCE_INFO_ERROR";
export const MARATHON_POD_INSTANCE_KILL_SUCCESS =
  "MARATHON_POD_INSTANCE_KILL_SUCCESS";
export const MARATHON_POD_INSTANCE_KILL_ERROR =
  "MARATHON_POD_INSTANCE_KILL_ERROR";
export const MARATHON_QUEUE_CHANGE = "MARATHON_QUEUE_CHANGE";
export const MARATHON_QUEUE_ERROR = "MARATHON_QUEUE_ERROR";
export const MARATHON_SERVICE_CREATE_ERROR = "MARATHON_SERVICE_CREATE_ERROR";
export const MARATHON_SERVICE_CREATE_SUCCESS =
  "MARATHON_SERVICE_CREATE_SUCCESS";
export const MARATHON_SERVICE_DELETE_ERROR = "MARATHON_SERVICE_DELETE_ERROR";
export const MARATHON_SERVICE_DELETE_SUCCESS =
  "MARATHON_SERVICE_DELETE_SUCCESS";
export const MARATHON_SERVICE_EDIT_ERROR = "MARATHON_SERVICE_EDIT_ERROR";
export const MARATHON_SERVICE_EDIT_SUCCESS = "MARATHON_SERVICE_EDIT_SUCCESS";
export const MARATHON_SERVICE_RESET_DELAY_ERROR =
  "MARATHON_SERVICE_RESET_DELAY_ERROR";
export const MARATHON_SERVICE_RESET_DELAY_SUCCESS =
  "MARATHON_SERVICE_RESET_DELAY_SUCCESS";
export const MARATHON_SERVICE_RESTART_ERROR = "MARATHON_SERVICE_RESTART_ERROR";
export const MARATHON_SERVICE_RESTART_SUCCESS =
  "MARATHON_SERVICE_RESTART_SUCCESS";
export const MARATHON_SERVICE_VERSION_CHANGE =
  "MARATHON_SERVICE_VERSION_CHANGE";
export const MARATHON_SERVICE_VERSION_ERROR = "MARATHON_SERVICE_VERSION_ERROR";
export const MARATHON_SERVICE_VERSIONS_CHANGE =
  "MARATHON_SERVICE_VERSIONS_CHANGE";
export const MARATHON_SERVICE_VERSIONS_ERROR =
  "MARATHON_SERVICE_VERSIONS_ERROR";
export const MARATHON_TASK_KILL_SUCCESS = "MARATHON_TASK_KILL_SUCCESS";
export const MARATHON_TASK_KILL_ERROR = "MARATHON_TASK_KILL_ERROR";
export const TASK_DIRECTORY_CHANGE = "TASK_DIRECTORY_CHANGE";
export const TASK_DIRECTORY_ERROR = "TASK_DIRECTORY_ERROR";
export const NODE_STATE_ERROR = "NODE_STATE_ERROR";
export const NODE_STATE_SUCCESS = "NODE_STATE_SUCCESS";
