#!/bin/bash

# Switch to branch or commit hash

if ! [ -z "$PLUGINS_CHECKOUT" ]; then
  cd dcos-ui-plugins
  git pull
  git checkout $PLUGINS_CHECKOUT
fi

cd /usr/src/dcos-ui
git pull
git checkout $APPLICATION_CHECKOUT

npm run --unsafe-perm preinstall
npm i

echo "module.exports = {'*': '$CLUSTER_ADDRESS'};" >> webpack/proxy.dev.js

npm start
