#!/bin/bash

set -e
[ -n "${DEBUG}" ] && set -x

# This file is intended to run on Jenkins, if you want to create a
# release locally, just run
# 1. npm run release
# followed by
# 2. git push --follow-tags ${BRANCH_NAME}

## Configuration
#####################################################################

# really create a release? (prevents accedential calling)
CREATE_RELEASE=${CREATE_RELEASE:-0}

# really push release? (prevents accedential calling)
PUSH_RELEASE=${PUSH_RELEASE:-0}

# get release target `master`` is fine, but if BRANCH_NAME is
# `release/1.11` we only want `1.11`
PKG_TARGET=$(echo ${BRANCH_NAME} | sed -E 's/([^/]*)$|./\1/g')

## Create Release and Push it
#####################################################################

# fetch whole repo (jenkins only checks out one sha)
git fetch

# checkout correct branch name (jenkins checks out a sha, not a named branch)
git checkout ${BRANCH_NAME}

# create relase with correct version number: PKG_TARGET+v<SEMVER>
if [ ${CREATE_RELEASE} -eq 0 ]; then
  echo "No release, no Bump!"
  exit 1
fi
npm run release

# push new release to branch, this pushes to the corresponsing release "master"!
if [ ${PUSH_RELEASE} -eq 0 ]; then
  echo "No push, no Bump!"
  exit 1
fi
git push --follow-tags https://$GIT_USER:$GIT_PASSWORD@github.com/dcos/dcos-ui ${BRANCH_NAME}
