#!/bin/bash

set -e
[ -n "${DEBUG}" ] && set -x

# This file is intended to run on Jenkins, if you want create a latest release locally,
# you need to provide some environment variables:
#
# GIT_COMMIT: Commit SHA to work on
# BRANCH_NAME: Branch Name to work on
# GIT_USER: git user for curl command
# GIT_PASSWORD: git password for curl command
# aws login credentials
#
# run these from project root:
# 1. npm run build
# 2. tar czf "release.tar.gz" dist
# 3. <get aws credentials setup in AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY>
# 4. FORCE_UPLOAD=1 BRANCH_NAME=$(git branch | grep \* | cut -d' ' -f2) GIT_COMMIT=$(git rev-parse HEAD) GIT_USER=<your_user> GIT_PASSWORD=<your_password> ./scripts/ci/release-latest

## Configuration
#####################################################################

# path of this file ()
SCRIPT_PATH="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && pwd)"

# project root for this file
PROJECT_ROOT="$( cd "$( echo ${SCRIPT_PATH} | sed s+/scripts/ci++)" && pwd )"

FORCE_UPLOAD=${FORCE_UPLOAD:-0}

# `master`` is fine, but if BRANCH_NAME is `release/1.11` we only want `1.11`
PKG_TARGET=$(echo ${BRANCH_NAME} | sed -E 's/([^/]*)$|./\1/g')
PKG_NAME="dcos-ui"
PKG_VERSION="latest"

DCOS_BRANCH="dcos-ui/${PKG_TARGET}/${PKG_NAME}-${PKG_VERSION}"

## Create Assets & Generate Upload Data
#####################################################################

FORCE_UPLOAD=${FORCE_UPLOAD} \
  PKG_TARGET=${PKG_TARGET} \
  PKG_NAME=${PKG_NAME} \
  PKG_VERSION=${PKG_VERSION} \
  ${SCRIPT_PATH}/utils/upload-build || exit 1


## Update DC/OS
#####################################################################

DCOS_BRANCH=${DCOS_BRANCH} \
  PKG_TARGET=${PKG_TARGET} \
  PKG_VERSION=${PKG_VERSION} \
  ${SCRIPT_PATH}/utils/update-dcos-repo || exit 1
