#!/bin/bash
set -ex

# Setup Git
git config --global user.email "$GIT_USER@users.noreply.github.com"
git config --global user.name "MesosphereCI Robot"
git clone --depth 1 "https://$GIT_USER:$GIT_PASSWORD@github.com/mesosphere/dcos" dcos-latest

# conditional if tag, checkout a new branch named like
if [[ $TAG_NAME ]]
then
  # checkout a new branch and open a new release PR
  git checkout -b "dcos-ui/$TAG_NAME"
  cp -fr buildinfo.json dcos-latest/packages/dcos-ui/buildinfo.json
  cd dcos-latest || exit 1

  git add "packages/dcos-ui/buildinfo.json"
  git commit -m "Update DC/OS UI to latest build"
  git push origin "dcos-ui/$TAG_NAME"

  # todo use Github API to make a PR with this branch
else
  # update this branch
  git checkout -b dcos-ui/latest
  cp -fr buildinfo.json dcos-latest/packages/dcos-ui/buildinfo.json
  cd dcos-latest || exit 1

  git add "packages/dcos-ui/buildinfo.json"
  git commit -m "Update DC/OS UI to latest build"
  git push origin dcos-ui/latest
fi


