#!/bin/bash
set -ex

# configuration
BUILD_VARIANT=${BUILD_VARIANT:-''}
BRANCH_NAME=${BRANCH_NAME:-'master'}

# aws settings
AWS_BUCKET='downloads.mesosphere.io'
BUCKET_PATH='dcos-ui'

# build release filename
FILENAME='dcos-ui'
PKG_BRANCH=$(echo ${BRANCH_NAME} | sed -E 's/([^/]*)$|./\1/g')
# ex. master+dcos-ui-v1_12_0-rc_1.tar.gz
RELEASE_NAME="${PKG_BRANCH}+${FILENAME}${BUILD_VARIANT}-v${PKG_VERSION}.tar.gz"

# tar dist
cd "dist"
tar czf "../$RELEASE_NAME" .
cd ..

BUILD_SHA=$(shasum ${RELEASE_NAME} | cut -d " " -f1)
ENCODED_RELEASE_NAME=$(echo ${RELEASE_NAME} | sed "s/\+/\%2B/g")
DOWNLOAD_URL=$(echo "https://${AWS_BUCKET}/${BUCKET_PATH}/${ENCODED_RELEASE_NAME}")
FILENAME='buildinfo.json'

# cat config to artifact file
cat <<EOF > ${FILENAME}
{
  "single_source": {
    "kind": "url_extract",
    "url": "${DOWNLOAD_URL}",
    "sha1": "${BUILD_SHA}"
  }
}
EOF

# upload
aws s3 cp $RELEASE_NAME s3://$AWS_BUCKET/$BUCKET_PATH/$RELEASE_NAME
