#!/bin/bash

set -e
set -x

# This file is intended to run on Jenkins, if you need to run it
# locally, you need to provide some environment variables:
#
# GIT_COMMIT: Commit SHA to work on
# BRANCH_NAME: Branch Name to work on
# GIT_USER: git user for curl command
# GIT_PASSWORD: git password for curl command
# SENTRY_AUTH_TOKEN: auth token for sentry.io
# aws login credentials
#
# run these commands from project root:
# 1. npm run build
# 2. tar czf "release.tar.gz" dist
# 3. <get aws credentials setup in AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY>
# 4. FORCE_UPLOAD=1 BRANCH_NAME=$(git branch | grep \* | cut -d' ' -f2) GIT_COMMIT=$(git rev-parse HEAD) GIT_USER=<your_user> GIT_PASSWORD=<your_password> ./scripts/ci/release-latest

## Configuration
#####################################################################

# path of this file
SCRIPT_PATH="$(cd $(dirname "$0")/$(dirname "$(readlink "$0")") && pwd)"

# project root for this file
PROJECT_ROOT="$( cd "$( echo "${SCRIPT_PATH}" | sed s+/scripts/ci++)" && pwd )"

# next release version (passed in by semantic-release)
PKG_VERSION="${1}"

# get correct DC/OS target (=base branch!) passed in from semantic-release
PKG_TARGET="${2}"

# build release name for branch and file names
# Examples:
# - master+dcos-ui-v2.0.1
# - 1.11+dcos-ui-v1.16.0
RELEASE_NAME="${PKG_TARGET}+dcos-ui-${PKG_VERSION}"

# latest dcos branch to work with
DCOS_BRANCH="dcos-ui/${PKG_TARGET}+dcos-ui-latest"

## Create Assets & Generate Upload Data
#####################################################################

VERSION_PLACEHOLDER="0.0.0-dev+semantic-release"

# first, replace placeholder in dist bundle and verify that it worked
sed -i'' "s/${VERSION_PLACEHOLDER}/${PKG_TARGET}+${PKG_VERSION}/" ${PROJECT_ROOT}/dist/index.html
if ! grep "${PKG_TARGET}+${PKG_VERSION}" "${PROJECT_ROOT}/dist/index.html"; then
  echo "Version injection into dist/index.html failed!"
  exit 1
fi

# second, create tarball
tar czf release.tar.gz dist

# third, upload tarball
# if this fails, there is already a release with this SHA -> stop.
RELEASE_NAME="${RELEASE_NAME}" \
  "${SCRIPT_PATH}/utils/upload-build" || exit 0

# Upload source maps to sentry.io
SENTRY_AUTH_TOKEN="${SENTRY_AUTH_TOKEN}" \
  RELEASE_NAME="${PKG_TARGET}+${PKG_VERSION}" \
  "${SCRIPT_PATH}/utils/upload-sourcemaps" || exit 0

## Update Latest DC/OS PR
#####################################################################

DCOS_BRANCH=${DCOS_BRANCH} \
  DCOS_ORIGIN="mesosphere/dcos" \
  DCOS_UPSTREAM="dcos/dcos" \
  PKG_TARGET=${PKG_TARGET} \
  PKG_VERSION=${PKG_VERSION} \
  "${SCRIPT_PATH}/utils/update-dcos-repo"
