#!/bin/bash
set -ex

# configuration
BUILD_VARIANT=${BUILD_VARIANT:-''}
BRANCH_NAME=${BRANCH_NAME:-'master'}
DIST_PATH=${DIST_PATH:-'dist'}
PACKAGE_PATH=${PACKAGE_PATH:-'.'}
SHA_SLUG=${SHA_SLUG:-$(git rev-parse --short HEAD)}

# aws settings
AWS_BUCKET='downloads.mesosphere.io'
BUCKET_PATH='dcos-ui'

# build release filename
FILENAME='dcos-ui'
PKG_VERSION=$(python -c "import sys, json; \
  pkg = json.load(open('$PACKAGE_PATH/package.json')); \
  sys.stdout.write(str(pkg['version']));")
PKG_BRANCH=$(echo ${BRANCH_NAME} | sed -E 's/([^/]*)$|./\1/g')
RELEASE_NAME="${PKG_BRANCH}+${FILENAME}${BUILD_VARIANT}-v${PKG_VERSION}+${SHA_SLUG}.tar.gz"

# tar dist
cd "$DIST_PATH"
tar czf "../$RELEASE_NAME" .
cd ..
BUILD_SHA=$(shasum ${RELEASE_NAME} | cut -d " " -f1)
ENCODED_RELEASE_NAME=$(echo ${RELEASE_NAME} | sed "s/\+/\%2B/g")
DOWNLOAD_URL=$(echo "https://${AWS_BUCKET}/${BUCKET_PATH}/${ENCODED_RELEASE_NAME}")
FILENAME='buildinfo.json'

# cat config to artifact file
cat <<EOF > ${FILENAME}
{
  "single_source": {
    "kind": "url_extract",
    "url": "${DOWNLOAD_URL}",
    "sha1": "${BUILD_SHA}"
  }
}
EOF

# upload
aws s3 cp $RELEASE_NAME s3://$AWS_BUCKET/$BUCKET_PATH/$RELEASE_NAME
