export const ACL_DIRECTORIES_CHANGED = "ACL_DIRECTORIES_CHANGED";
export const ACL_DIRECTORIES_ERROR = "ACL_DIRECTORIES_ERROR";
export const ACL_DIRECTORY_ADD_SUCCESS = "ACL_DIRECTORY_ADD_SUCCESS";
export const ACL_DIRECTORY_ADD_ERROR = "ACL_DIRECTORY_ADD_ERROR";
export const ACL_DIRECTORY_DELETE_SUCCESS = "ACL_DIRECTORY_DELETE_SUCCESS";
export const ACL_DIRECTORY_DELETE_ERROR = "ACL_DIRECTORY_DELETE_ERROR";
export const ACL_DIRECTORY_TEST_SUCCESS = "ACL_DIRECTORY_TEST_SUCCESS";
export const ACL_DIRECTORY_TEST_ERROR = "ACL_DIRECTORY_TEST_ERROR";
