export const CERTIFICATE_ALL_CERTIFICATES_ERROR =
  "CERTIFICATE_ALL_CERTIFICATES_ERROR";
export const CERTIFICATE_ALL_CERTIFICATES_SUCCESS =
  "CERTIFICATE_ALL_CERTIFICATES_SUCCESS";
export const SECRET_ALL_STORES_ERROR = "SECRET_ALL_STORES_ERROR";
export const SECRET_ALL_STORES_SUCCESS = "SECRET_ALL_STORES_SUCCESS";
export const SECRET_STORE_CREATE_SECRET_ERROR =
  "SECRET_STORE_CREATE_SECRET_ERROR";
export const SECRET_STORE_CREATE_SECRET_SUCCESS =
  "SECRET_STORE_CREATE_SECRET_SUCCESS";
export const SECRET_STORE_DELETE_SECRET_SUCCESS =
  "SECRET_STORE_DELETE_SECRET_SUCCESS";
export const SECRET_STORE_DELETE_SECRET_ERROR =
  "SECRET_STORE_DELETE_SECRET_ERROR";
export const SECRET_STORE_RENEW_SECRET_ERROR =
  "SECRET_STORE_RENEW_SECRET_ERROR";
export const SECRET_STORE_RENEW_SECRET_SUCCESS =
  "SECRET_STORE_RENEW_SECRET_SUCCESS";
export const SECRET_STORE_REVOKE_SECRET_ERROR =
  "SECRET_STORE_REVOKE_SECRET_ERROR";
export const SECRET_STORE_REVOKE_SECRET_SUCCESS =
  "SECRET_STORE_REVOKE_SECRET_SUCCESS";
export const SECRET_STORE_SEAL_STATUS_ERROR = "SECRET_STORE_SEAL_STATUS_ERROR";
export const SECRET_STORE_SEAL_STATUS_SUCCESS =
  "SECRET_STORE_SEAL_STATUS_SUCCESS";
export const SECRET_STORE_SECRETS_ERROR = "SECRET_STORE_SECRETS_ERROR";
export const SECRET_STORE_SECRETS_SUCCESS = "SECRET_STORE_SECRETS_SUCCESS";
export const SECRET_STORE_SECRET_ERROR = "SECRET_STORE_SECRET_ERROR";
export const SECRET_STORE_SECRET_SUCCESS = "SECRET_STORE_SECRET_SUCCESS";
export const SECRET_STORE_UPDATE_SECRET_ERROR =
  "SECRET_STORE_UPDATE_SECRET_ERROR";
export const SECRET_STORE_UPDATE_SECRET_SUCCESS =
  "SECRET_STORE_UPDATE_SECRET_SUCCESS";
