#!/bin/bash
# This script is executed in the development docker image when the user
# runs any command within it. It's purpose is to check the if scaffolding
# is needed and apply it.

#
# Pass through commands or run `tail -f /dev/null` to keep the container alive
# when started in background
#
if [[ -n $* ]]; then
  eval $*
else
  tail -f /dev/null
fi
