#!/usr/bin/env bash
SCRIPT_PATH="$(dirname "$0")/$(dirname "$(readlink "$0")")"

# Import utils
source "${SCRIPT_PATH}/utils/message"

title "lingui extract"

VERBOSE=""
if [[ $* == *--verbose* ]]; then
  VERBOSE="--verbose "
fi

info "Extracting message catalogs for dcos-ui..."
eval "lingui extract $VERBOSE--clean --config ./linguirc"
if [ -d "$SCRIPT_PATH/../plugins-ee" ]; then
  if [[ $? == 0 ]]; then
    info "Extracting message catalogs for dcos-ui-plugins-private"
    eval "lingui extract $VERBOSE--clean  --config ./plugins-ee/.linguirc"
  fi
fi
