#!/usr/bin/env bash

SCRIPT_PATH="$(dirname "$0")/$(dirname "$(readlink "$0")")"

# Import utils
source "${SCRIPT_PATH}/utils/message"

function sanityCheck {
  if [ ! -d "$SCRIPT_PATH/../plugins-ee" ]; then
    warning "Extraction tooling currently requires enterprise plugins to be linked with this repo. Please seek assistance from a DC/OS Github admin for more info"
    return 1
  elif [ ! -f "$SCRIPT_PATH/../.babelrc" ]; then
    warning "plugins-ee/.babelrc file not found. Did this script fail previously? Try running with --unpatch to fix"
    return 1
  else
    return 0
  fi
}

# lingui extract cannot extract messages from macros that are outside of the package
# due to the way packages are resolved from each source file. This script creates a temporary symlink
# to the conventional dcos-ui-plugins-private directory and also temporarily hides the .babelrc file
# which is not useful when followed through the symlink
function patch {
  info "Temporarily renaming .babelrc for lingui extract tooling"
  mv "$SCRIPT_PATH/../plugins-ee/.babelrc" "$SCRIPT_PATH/../plugins-ee/.tmp.babelrc"
}

function unpatch {
  mv "$SCRIPT_PATH/../plugins-ee/.tmp.babelrc" "$SCRIPT_PATH/../plugins-ee/.babelrc"
  info "Restored .babelrc"
}

title "Running lingui extract for dcos-ui and dcos-ui-plugins-private"

VERBOSE=""
if [[ $* == *--verbose* ]]; then
  VERBOSE="--verbose "
fi

sanityCheck
if [[ $? == 0 ]]; then
  patch
  info "This may take a minute..."
  eval "lingui extract $VERBOSE--clean"
  unpatch
elif [[ $* == *--unpatch ]]; then
  unpatch
fi
