#!/usr/bin/env bash

SCRIPT_PATH="$(dirname "$0")/$(dirname "$(readlink "$0")")"

# Import utils
source "${SCRIPT_PATH}/utils/message"

# lingui extract cannot extract messages from macros that are outside of the package
# due to the way packages are resolved from each source file. This script creates a temporary symlink
# to the conventional dcos-ui-plugins-private directory and also temporarily hides the .babelrc file
# which is not useful when followed through the symlink
function patch {
  info "Temporarily swapping .linguirc for external plugins compilation..."
  mv "$SCRIPT_PATH/../.linguirc" "$SCRIPT_PATH/../.tmp.linguirc"
  cp "$SCRIPT_PATH/../plugins-ee/.linguirc.ee" "$SCRIPT_PATH/../.linguirc"
}

function unpatch {
  rm "$SCRIPT_PATH/../.linguirc"
  mv "$SCRIPT_PATH/../.tmp.linguirc" "$SCRIPT_PATH/../.linguirc"
  info "Deleted temporary linguirc config"
}

title "lingui compile"

if [[ $? == 0 ]]; then
  info "Compiling message catalogs for dcos-ui..."
  eval "lingui compile"
  if [ -d "$SCRIPT_PATH/../plugins-ee" ]; then
    info "Compiling message catalogs for dcos-ui-plugins-private"
    patch
    eval "lingui compile"
    unpatch
  fi
elif [[ $* == *--unpatch ]]; then
  unpatch
fi
