#!/usr/bin/env bash

SCRIPT_PATH="$(dirname "$0")/$(dirname "$(readlink "$0")")"

# Import utils
source "${SCRIPT_PATH}/utils/message"

title "lingui compile"

info "Compiling message catalogs for dcos-ui..."
eval "lingui compile --config ./linguirc"
