#!/usr/bin/env bash

SCRIPT_PATH="$(dirname "$0")/$(dirname "$(readlink "$0")")"

# Import utils
source ${SCRIPT_PATH}/utils/message

title "Run post-rewrite hook..."

header "Run lint..."
npm run lint &&
if [ "undefined" != `npm config get externalplugins` ]; then
  npm run lint-plugins || exit $?
fi
