#!/usr/bin/env bash

SCRIPT_PATH="$(dirname "$0")/$(dirname "$(readlink "$0")")"
MARATHON_TAG="1.4.0-snap25"

# Import utils
source ${SCRIPT_PATH}/utils/git
source ${SCRIPT_PATH}/utils/marathon

# Validate node and npm version and install git hooks
${SCRIPT_PATH}/validate-engine-versions && install_hooks "pre-commit" && \
  install_marathon_raml "$MARATHON_TAG"

exit 0
