#!/usr/bin/env bash

# Import utils
source ${0%/*}/utils/git
source ${0%/*}/utils/message

title "Run pre-commit hook..."

# Get a list of staged javascript files and only lint changed files
staged_javascript_files=$(get_staged_files_with_name '*.js');
if [ -n "${staged_javascript_files}" ]
then
  header "Lint staged js files"
  npm run eslint --silent -- ${staged_javascript_files}
fi


# Get a list of staged less files and only lint changed files
staged_less_files=$(get_staged_files_with_name '*.less');
if [ -n "${staged_less_files}" ]
then
  header "Lint staged less files"
  npm run stylelint --silent -- ${staged_less_files}
fi
