#!/usr/bin/env bash

SCRIPT_PATH="$(dirname "$0")/$(dirname "$(readlink "$0")")"

# Import utils
source ${SCRIPT_PATH}/utils/git
source ${SCRIPT_PATH}/utils/message

title "Run pre-commit hook..."

# Get a list of staged JavaScript and Less files
staged_javascript_files=$(get_staged_files_with_name '*.js');
staged_less_files=$(get_staged_files_with_name '*.less');

# Lint staged JavaScript and Less files
if [ -n "${staged_javascript_files}" ]
then
  header "Lint staged JavaScript files..."
  npm run eslint --silent -- ${staged_javascript_files} || exit $?
  info "Staged JavaScript looks good"
fi
if [ -n "${staged_less_files}" ]
then
  header "Lint staged Less files..."
  npm run stylelint --silent -- ${staged_less_files} || exit $?
  info "Staged Less looks good"
fi

# Test staged JavaScript files
if [ -n "${staged_javascript_files}" ]
then
  header "Test staged JavaScript files.."
  npm run test --silent -- --findRelatedTests \
    ${staged_javascript_files} || exit $?
fi
