#!/usr/bin/env bash

SCRIPT_PATH="$(dirname "$0")/$(dirname "$(readlink "$0")")"

# Import utils
source ${SCRIPT_PATH}/utils/git
source ${SCRIPT_PATH}/utils/messages

${SCRIPT_PATH}/validate-tests

title "Lint commit messages..."

fork_point=$(get_fork_point)
linting_errors="$(
  npm run conventional-changelog-lint --silent -- -f ${fork_point} -t HEAD;
  echo x$?
)"

if [  ${linting_errors##*x} -ne 0 ]
then
  warning "Wrong commit message format"

  echo -e "Please align all reported commit messages with the formatting"\
  "rules documented in our contributing guidelines (CONTRIBUTING.md)."\
   "\n\n${linting_errors%x*}"\
   "\nUse the following command to edit the commits and change message."\
   "\n\n> git rebase -i ${fork_point}\n"
  exit 1
fi

info "Commit messages looks good"
exit 0
