#!/usr/bin/env bash

SCRIPT_PATH="$(dirname "$0")/$(dirname "$(readlink "$0")")"
MARATHON_VERSION="1.11.2-7cde07166"

# Import utils
source "${SCRIPT_PATH}/utils/git"
source "${SCRIPT_PATH}/utils/marathon"

# Install Marathon RAML before hooks so RAML isn't skipped in CI if
# git hooks fail to install
install_marathon_raml "$MARATHON_VERSION" && \
  install_hooks "pre-commit post-commit post-checkout"

exit 0
