#!/usr/bin/env bash

SCRIPT_PATH="$(dirname "$0")/$(dirname "$(readlink "$0")")"
MARATHON_VERSION="1.4.2"

# Import utils
source ${SCRIPT_PATH}/utils/git
source ${SCRIPT_PATH}/utils/marathon

# Validate node and npm version and install git hooks.
# Install Marathon RAML before hooks so RAML isn't skipped in CI if
# git hooks fail to install
${SCRIPT_PATH}/validate-engine-versions && \
  install_marathon_raml "$MARATHON_VERSION" && \
  install_hooks "pre-commit post-rewrite"

exit 0
