#!/usr/bin/env bash

SCRIPT_PATH="$(dirname "$0")/$(dirname "$(readlink "$0")")"

# Import utils
source "${SCRIPT_PATH}/utils/git"
source "${SCRIPT_PATH}/utils/message"
source "${SCRIPT_PATH}/utils/test"

title "Run pre-push hook..."

fork_point=$(get_fork_point)

header "Validate staged JavaScript tests..."
debug_directives=$(
  find_debug_directives $(git diff --name-only "${fork_point}" HEAD  -- "*.js")
)

if [ -n "${debug_directives}" ]
then
  warning "Debug directives found"

  echo -e "Please remove all found debug directives" \
   "before committing your changes. \n" \
   "${debug_directives}"

  exit 1
fi
info "Staged JavaScript tests looks good"

header "Lint commit messages..."
linting_errors="$(
  npm run lint:commits --silent -- -f "${fork_point}" -t HEAD;
  echo x$?
)"

if [  "${linting_errors##*x}" -ne 0 ]
then
  warning "Wrong commit message format"

  echo -e "Please align all reported commit messages with the formatting"\
  "rules documented in our contributing guidelines (CONTRIBUTING.md)."\
   "\n\n${linting_errors%x*}"\
   "\nUse the following command to edit the commits and change message."\
   "\n\n> git rebase -i ${fork_point}\n"
  exit 1
fi

info "Commit messages looks good"
exit 0
