#!/usr/bin/env bash

SCRIPT_PATH="$(dirname "$0")/$(dirname "$(readlink "$0")")"

# Import utils
source ${SCRIPT_PATH}/utils/message

header "Validating tests..."

! egrep -R "fdescribe\\(|fit\(" ./src || exit 1 && \
! egrep -R "context\.only\(|it\.only\(" ./tests || exit 1

exit 0
