#!/usr/bin/env bash

SCRIPT_PATH="$(dirname "$0")/$(dirname "$(readlink "$0")")"

# Import utils
source ${SCRIPT_PATH}/utils/git

header "Validating tests..."

! egrep --quiet -R "fdescribe\\(|fit\(" ./src && \
! egrep --quiet -R "context\.only\(|it\.only\(" ./tests

exit 0
