#!/bin/bash

if [ -z "$(dcos package list | grep dcos-enterprise-cli)" ]; then
  dcos package install dcos-enterprise-cli --yes
fi

# Create a service group for the test
cat <<EOF | dcos marathon group add
{
  "id": "/$TEST_UUID"
}
EOF
