#!/bin/bash

# Remove the service group for the test
dcos marathon group remove /$TEST_UUID

# Remove the secret with this UUID (and don't fail if it doesn't exist)
dcos security secrets delete /$TEST_UUID-secret || exit 0
