export const REQUEST_LICENSING_SUMMARY_ERROR =
  "REQUEST_LICENSING_SUMMARY_ERROR";
export const REQUEST_LICENSING_SUMMARY_SUCCESS =
  "REQUEST_LICENSING_SUMMARY_SUCCESS";
export const REQUEST_LICENSING_FILE_ERROR = "REQUEST_LICENSING_FILE_ERROR";
export const REQUEST_LICENSING_FILE_SUCCESS = "REQUEST_LICENSING_FILE_SUCCESS";
