export const LICENSING_SUMMARY_SUCCESS = "LICENSING_SUMMARY_SUCCESS";
export const LICENSING_SUMMARY_ERROR = "LICENSING_SUMMARY_ERROR";
export const LICENSING_FILE_ERROR = "LICENSING_FILE_ERROR";
export const LICENSING_FILE_SUCCESS = "LICENSING_FILE_SUCCESS";
